FROM python:3.10.8

WORKDIR /Backend
RUN pip install --upgrade pip
RUN pip install flask
RUN pip install flask_cors
RUN pip install streamlit
RUN pip install matplotlib
RUN pip install numpy
RUN pip install sklearn
RUN pip install scikit-learn
RUN pip install werkzeug
RUN pip install pandas

COPY . .

EXPOSE 5000

CMD [ "python",'main.py' ]